function [fitresult, gof] = createFit(L, R, Data)
%CREATEFIT(L,R,DATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: L from thumb_q1
%      Y Input: R from thumb_q1
%      Z Output: Data from thumb_q1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Dec-2024 23:17:32


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( L, R, Data );

% Set up fittype and options.
ft = 'nearestinterp';
opts = fitoptions( 'Method', 'NearestInterpolant' );
opts.ExtrapolationMethod = 'nearest';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'Data vs. L, R', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'L', 'Interpreter', 'none' );
ylabel( 'R', 'Interpreter', 'none' );
zlabel( 'Data', 'Interpreter', 'none' );
grid on
view( -24.7, 32.2 );


